# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26c453ae0859a8f76beba9ab4b3336c95bd5fe74555558221ffd9a4345182c5c04e0407d510cbd5b8ea68338942fe53d64684bd4c6f44f9e69f901b0bc890b33

test:
  secret_key_base: 45a0c99dc3256754d352ff763fdbde5275a72824eeb8906ade5752712a566c6418c5fa3c56e8134ae48097f03f3fcd18a376218fd2778cb07c3dd71dc88565b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
